default_platform(:ios)

platform :ios do
  desc "Build and release iOS app"
  lane :release do
    # TODO: implement
  end
end

platform :android do
  desc "Build and release Android app"
  lane :release do
    # TODO: implement
  end
end
